### PR TITLE
Feature/download mapped jsons from sync rules

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References

-   **Issue:** Closes https://app.clickup.com/t/crvvrf

### :memo: Implementation

- [x] Create a new use case to download mapped payload  from a sync rule
- [x] Invoke the new download use case from the sync rules page
- [x] Invoke the new download use case from the sync summary step

### :bookmark_tabs: Others

-   Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

-   Any change in the [D2 Api](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?

### CODE REVIEW

**Comment by SferaDev** [comment]
Since we are now adding the ``instanceRepository.getById``, could we use that method on [GetInstanceByIdUseCase](https://github.com/EyeSeeTea/metadata-synchronization/blob/feature/download_mapped_jsons_from_sync_rules/src/domain/instance/usecases/GetInstanceByIdUseCase.ts) ?

**Comment by EyeSeeTeaBotTest** [comment]
<h3>Tests failed with errors :rotating_light:</h3><br />Build commit Merge 61cd195870fcfc122b38fe155789214459639a92 into c2d2380ca6bf2a90c3de00eccd80e76638196b43 with commit id 3a79c17d2c631ccc4cdfef75400ad88e20d51621 on branch feature/download_mapped_jsons_from_sync_rules<br /><br />Travis log available at <a href=https://travis-ci.org/EyeSeeTea/metadata-synchronization/builds/759455642 target=_blank>builds/759455642</a><br /><br />See cypress results at <a href=https://eyeseetea.github.io/feedback-ci/EyeSeeTea/metadata-synchronization/pr/828/3a79c17d2c631ccc4cdfef75400ad88e20d51621 target=_blank>feedback-ci/EyeSeeTea/metadata-synchronization/pr/828/3a79c17d2c631ccc4cdfef75400ad88e20d51621</a>

**Comment by xurxodev** [comment]
@SferaDev Yes! but really there are many use cases that may be refactored to avoid duplicate code using this new method in the InstanceRepository:
* GetInstanceByIdUseCase
* CancelPullRequestUseCase
* ImportPullRequestUseCase
* ListNotificationsUseCase
* GenericSyncUseCase
* PrepareSyncUseCase

As it is not an one use case to refactor, I prefer to talk to @adrianq about the best moment to do it because we have not tests for these use cases, then it implies manually testing each use case.

**Comment by xurxodev** [comment]
@SferaDev I have talked with @adrianq to create a new issue to do this refactor -> https://app.clickup.com/t/ef4fwm

**Pull request merged**
