### PR TITLE
Use d2-api with fetch backend

### LINKED ISSUE #655: Support fetch mode
- [x] NetworkRepository
- [x] AxiosNetworkRepository
- [x] FetchNetworkRepository (with auth/credentials logic)
- [x] Integrate in project-monitoring
- [x] Integrate in metadata-sync

### PR DESCRIPTION
**Pull request by tokland**
### :pushpin: References

-   **Issue:** Closes #655
- Uses https://github.com/EyeSeeTea/d2-api/pull/59

### :memo: Implementation

- `getD2APiFromInstance` to keep the code DRY
- axiosRetry removed. If we decide to keep a retry mechanism we'll need to modify d2-api.

### :fire: Is there anything the reviewer should know to test it?

I've done a general testing using the same domain (localhost) and different ports. When using the old d2-api (axios), my main session got lost, now everything seems to work fine.

### CODE REVIEW

**Comment by EyeSeeTeaBotTest** [comment]
<h3>Tests failed with errors :rotating_light:</h3><br />Build commit Merge ff71a4f592de8f7521eb80b04b3d1b18f7ba9299 into dd7edb8f84c95f0c470859d816f29df5e17af178 with commit id 5deb53a4b93775462416543da711aea27f10ef2e on branch feature/instances-fetch-backend-655<br /><br />Travis log available at <a href=https://travis-ci.org/EyeSeeTea/metadata-synchronization/builds/732875640 target=_blank>builds/732875640</a><br /><br />See cypress results at <a href=https://eyeseetea.github.io/feedback-ci/EyeSeeTea/metadata-synchronization/pr/657/5deb53a4b93775462416543da711aea27f10ef2e target=_blank>feedback-ci/EyeSeeTea/metadata-synchronization/pr/657/5deb53a4b93775462416543da711aea27f10ef2e</a>

**Review by SferaDev — APPROVED** [review]
LGTM!

**Comment by adrianq** [comment]
@SferaDev @tokland First things first, amazing work in so little time! It works like a charm! Thanks guys!

Now, two questions:
- We are losing the re-try capability that was only used in the migration framework, right?
- @SferaDev You mentioned yesterday that you were having a hard time trying to make it work as node script installed on the server. How did it go at the end? Did you manage to solve it?

**Comment by SferaDev** [comment]
> - We are losing the re-try capability that was only used in the migration framework, right?

Yes, right now we do not have retrying nor caching which should be considered in the future on the API side. 

> - @SferaDev You mentioned yesterday that you were having a hard time trying to make it work as node script installed on the server. How did it go at the end? Did you manage to solve it?

Working properly now, you can give it a quick test if you want and release a new scheduler version too.

**Pull request merged**
