### PR TITLE
Add select children action in events sync rule (8)

### LINKED ISSUE #723: Select children in sync rule for Program (parent) + PI (children). (B7)

### PR DESCRIPTION
**Pull request by xurxodev**
### :pushpin: References

-   **Issue:** Closes #723

### :memo: Implementation

- [x] Add select children action in events sync rule

### :art: Screenshots

Captura de pantalla 2020-12-10 a las 13 15 17

### :bookmark_tabs: Others

-   Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

-   Any change in the [D2 Api](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?

### CODE REVIEW

**Comment by adrianq** [comment]
@xurxodev There seems to be a bug that maybe was around already. When you select the children of a program, any other selection is automatically unselected. The idea is that this 'select children' functionality will just add new items to the selection

**Comment by xurxodev** [comment]
@adrianq  Fixed!

**Comment by SferaDev** [comment]
@adrianq Including the test fixes in this PR: https://github.com/EyeSeeTea/metadata-synchronization/pull/750/commits/ae802f68235517126817f7e7840cb66695706386

**Comment by adrianq** [comment]
Increasing the timeout and using '!important' in css you can probably conquer the middle Earth and part of Central Mongolia. Thanks!

**Pull request merged**
