### PR TITLE
fix: fixing scheduler build

### PR DESCRIPTION
**Pull request by 9sneha-n**
### :pushpin: References

-   **Issue:** Closes #? partial : https://app.clickup.com/t/8694w3grg, #8694w3grg

### :memo: Implementation
Fix Scheduler build.
-

### :fire: Is there anything the reviewer should know to test it?

run `yarn build-scheduler` - a zip should be generated successfully.

### :bookmark_tabs: Others

-   Any change in the [GUI library](https://github.com/EyeSeeTea/d2-ui-components)? If so, what branch/PR?

-   Any change in the [D2 Api](https://github.com/EyeSeeTea/d2-api)? If so, what branch/PR?

### CODE REVIEW

**Comment by ifoche** [comment]
Task linked: [CU-8694w3grg eIDSR Integration Design and Dev](https://app.clickup.com/t/8694w3grg)

**Review by tokland — APPROVED** [review]
As discussed, it's a not a critical component, it can be downgraded if that solves build problem. Eventually it should be updated, though.

**Comment by 9sneha-n** [comment]
@MiquelAdell  Could you please merge this and create a release as we need to share the Scheduler zip with Zebra client.

**Review by ifoche — APPROVED** [review]
thanks @9sneha-n

**Pull request merged**
