### PR TITLE
[Feature] Highlight red rows for conflicted data elements

### LINKED ISSUE #430: Show red highlighting for conflicting DEs in event
Done in Samaritans

### LINKED ISSUE #484: Change pop-up title to sth like 'select Data Element from Destination instance {destinationinstance} to map {element}'

### PR DESCRIPTION
**Pull request by SferaDev**
### :pushpin: References

* **Issue:** Closes #430 
* **Issue:** Closes #484

### :memo: Implementation

- Update mapping dialog title,
- Add red rows for conflicted data elements in event sync
- Fix sync summary cancel callback
- Add updates implemented in scheduler

### :art: Screenshots

image

### CODE REVIEW

**Comment by EyeSeeTeaBotTest** [comment]
<h3>Tests failed with errors :rotating_light:</h3><br />Build commit Merge 54487c065cc5c1bb7fd8473d6f2d70b7c41b3843 into b37a4179824b2bb5c909e790c22faba77d493670 with commit id 93db9af5c7cafd4414fbc2ae8900ff60c06db58a on branch feature/red-rows<br /><br />Travis log available at <a href=https://travis-ci.org/EyeSeeTea/metadata-synchronization/builds/668843541 target=_blank>builds/668843541</a><br /><br />See cypress results at <a href=https://eyeseetea.github.io/feedback-ci/EyeSeeTea/metadata-synchronization/pr/489/93db9af5c7cafd4414fbc2ae8900ff60c06db58a target=_blank>feedback-ci/EyeSeeTea/metadata-synchronization/pr/489/93db9af5c7cafd4414fbc2ae8900ff60c06db58a</a>

**Comment by SferaDev** [comment]
Updated this PR with https://github.com/EyeSeeTea/metadata-synchronization/pull/474#issuecomment-606626346

**Comment by adrianq** [comment]
Thanks, @SferaDev Two comments:
- If a program is excluded, probably we don't want to show rows highlighted
- I have noticed a non-related bug if a program is excluded and we apply automap it cannot find a match even if there is one

**Comment by adrianq** [comment]
Will keep #430 open and drop above comments there

**Pull request merged**
