### PR TITLE
Basic Validation Rules Sync

### LINKED ISSUE #10: Implement Indicator Sync
Sync Logic: sync indicators, indicators groups and indicator group sets and their attributes.

### LINKED ISSUE #11: Implement Validation Rules Sync

### PR DESCRIPTION
**Pull request by SferaDev**
### :pushpin: References

* **Issue:** Closes #11 

* **Status:** Tested with Validation Rule with a group and attributes set to both of them.

### :memo: Implementation

- Include attributes

- Include validationRuleGroups (with attributes and do not include the child validation rules)

### :art: Metadata package

```json
{
    "validationRules": [
        {
            "code": "test01",
            "lastUpdated": "2019-04-26T12:23:12.736",
            "id": "SF7fBhU8jDw",
            "created": "2019-04-26T12:18:05.470",
            "name": "Test01",
            "importance": "MEDIUM",
            "displayName": "Test01",
            "publicAccess": "rw------",
            "operator": "not_equal_to",
            "externalAccess": false,
            "dimensionItem": "SF7fBhU8jDw",
            "periodType": "Monthly",
            "skipFormValidation": false,
            "favorite": false,
            "access": {
                "read": true,
                "update": true,
                "externalize": true,
                "delete": true,
                "write": true,
                "manage": true
            },
            "leftSide": {
                "expression": "#{KnQn2N452bE.wyZ6KAmjZeD}",
                "description": "test",
                "missingValueStrategy": "NEVER_SKIP",
                "slidingWindow": false
            },
            "lastUpdatedBy": {
                "id": "OiCDrIyOSdG"
            },
            "rightSide": {
                "expression": "#{fG0NDp9ZcQh.wyZ6KAmjZeD}",
                "description": "test2",
                "missingValueStrategy": "NEVER_SKIP",
                "slidingWindow": false
            },
            "validationRuleGroups": [
                {
                    "id": "ej36HOumL9b"
                }
            ],
            "favorites": [],
            "organisationUnitLevels": [
                1,
                2,
                3,
                4,
                5,
                6
            ],
            "notificationTemplates": [],
            "translations": [],
            "attributeValues": [
                {
                    "lastUpdated": "2019-04-26T12:23:12.711",
                    "created": "2019-04-26T12:23:12.711",
                    "value": "1000",
                    "attribute": {
                        "id": "wmouu8FpqAp"
                    }
                }
            ]
        }
    ],
    "validationRuleGroups": [
        {
            "code": "test01",
            "created": "2019-04-26T12:17:36.363",
            "lastUpdated": "2019-04-26T12:23:29.071",
            "name": "Test01",
            "id": "ej36HOumL9b",
            "displayName": "Test01",
            "publicAccess": "rw------",
            "externalAccess": false,
            "favorite": false,
            "lastUpdatedBy": {
                "id": "OiCDrIyOSdG"
            },
            "access": {
                "read": true,
                "update": true,
                "externalize": true,
                "delete": true,
                "write": true,
                "manage": true
            },
            "favorites": [],
            "attributeValues": [
                {
                    "lastUpdated": "2019-04-26T12:23:29.053",
                    "created": "2019-04-26T12:23:29.053",
                    "value": "test@me.com",
                    "attribute": {
                        "id": "vYuOA7WHC6M"
                    }
                }
            ],
            "translations": []
        }
    ],
    "attributes": [
        {
            "lastUpdated": "2019-04-26T12:22:46.995",
            "id": "vYuOA7WHC6M",
            "created": "2019-04-26T12:22:46.995",
            "name": "Test02",
            "code": "test02",
            "indicatorAttribute": false,
            "indicatorGroupAttribute": false,
            "publicAccess": "rw------",
            "userGroupAttribute": false,
            "dataElementAttribute": false,
            "constantAttribute": false,
            "valueType": "EMAIL",
            "categoryOptionAttribute": false,
            "optionSetAttribute": false,
            "sqlViewAttribute": false,
            "legendSetAttribute": false,
            "trackedEntityAttributeAttribute": false,
            "organisationUnitAttribute": false,
            "dataSetAttribute": false,
            "documentAttribute": false,
            "unique": false,
            "validationRuleGroupAttribute": true,
            "favorite": false,
            "dataElementGroupAttribute": false,
            "sectionAttribute": false,
            "trackedEntityTypeAttribute": false,
            "userAttribute": false,
            "displayName": "Test02",
            "mandatory": false,
            "categoryOptionGroupAttribute": false,
            "externalAccess": false,
            "programStageAttribute": false,
            "programAttribute": false,
            "categoryAttribute": false,
            "categoryOptionComboAttribute": false,
            "categoryOptionGroupSetAttribute": false,
            "validationRuleAttribute": true,
            "programIndicatorAttribute": false,
            "organisationUnitGroupAttribute": false,
            "dataElementGroupSetAttribute": false,
            "organisationUnitGroupSetAttribute": false,
            "optionAttribute": false,
            "lastUpdatedBy": {
                "id": "OiCDrIyOSdG"
            },
            "access": {
                "read": true,
                "update": true,
                "externalize": true,
                "delete": true,
                "write": true,
                "manage": true
            },
            "user": {
                "id": "OiCDrIyOSdG"
            },
            "translations": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "userAccesses": [],
            "favorites": []
        },
        {
            "lastUpdated": "2019-04-26T12:22:25.253",
            "id": "wmouu8FpqAp",
            "created": "2019-04-26T12:22:25.253",
            "name": "Test01",
            "code": "test01",
            "indicatorAttribute": false,
            "indicatorGroupAttribute": false,
            "publicAccess": "rw------",
            "userGroupAttribute": false,
            "dataElementAttribute": false,
            "constantAttribute": false,
            "valueType": "INTEGER",
            "categoryOptionAttribute": false,
            "optionSetAttribute": false,
            "sqlViewAttribute": false,
            "legendSetAttribute": false,
            "trackedEntityAttributeAttribute": false,
            "organisationUnitAttribute": false,
            "dataSetAttribute": false,
            "documentAttribute": false,
            "unique": false,
            "validationRuleGroupAttribute": true,
            "favorite": false,
            "dataElementGroupAttribute": false,
            "sectionAttribute": false,
            "trackedEntityTypeAttribute": false,
            "userAttribute": false,
            "displayName": "Test01",
            "mandatory": false,
            "categoryOptionGroupAttribute": false,
            "externalAccess": false,
            "programStageAttribute": false,
            "programAttribute": false,
            "categoryAttribute": false,
            "categoryOptionComboAttribute": false,
            "categoryOptionGroupSetAttribute": false,
            "validationRuleAttribute": true,
            "programIndicatorAttribute": false,
            "organisationUnitGroupAttribute": false,
            "dataElementGroupSetAttribute": false,
            "organisationUnitGroupSetAttribute": false,
            "optionAttribute": false,
            "lastUpdatedBy": {
                "id": "OiCDrIyOSdG"
            },
            "access": {
                "read": true,
                "update": true,
                "externalize": true,
                "delete": true,
                "write": true,
                "manage": true
            },
            "user": {
                "id": "OiCDrIyOSdG"
            },
            "translations": [],
            "userGroupAccesses": [],
            "attributeValues": [],
            "userAccesses": [],
            "favorites": []
        }
    ]
}
```

### CODE REVIEW

**Comment by adrianq** [comment]
@SferaDev Can you refresh my mind why we are synchronising the validationRulesGroups _with attributes and do not include the child validation rules_ ?

**Comment by SferaDev** [comment]
> @SferaDev Can you refresh my mind why we are synchronising the validationRulesGroups _with attributes and do not include the child validation rules_ ?

Yes, imagine the following scenario: We select one ValidationRule assigned to a Group. We want to import the group but we do not want to parse other ValidationRules that are also assigned to the same group but the user didn't originally select.

**Comment by adrianq** [comment]
Got it! ... but then we need to do some kind of postprocessing and add the Group with only the selected Validation Rules (created an issue for this https://github.com/orgs/EyeSeeTea/projects/23#card-21111811) Btw, what are we currently doing with the Org Units Groups in this concern?

**Comment by SferaDev** [comment]
> Got it! ... but then we need to do some kind of postprocessing and add the Group with only the selected Validation Rules (created an issue for this https://github.com/orgs/EyeSeeTea/projects/23#card-21111811) Btw, what are we currently doing with the Org Units Groups in this concern?

We're doing the same approach for OU/OUGroups.

I believe there's no need to post-assign the elements to their groups because they already contain a link as children to their parent group and DHIS2 **should**assign them on import. But I believe the card is fine to double check the expected behavior is actually what DHIS2 does.

**Comment by adrianq** [comment]
Mmm the main problem I found is that from the Maintenance DHIS2 app children are not visible and this may be confusing for the user

**Pull request merged**
